# warehouse:
#   target: dev
#   outputs:
#     dev:
#       type: postgres
#       host: "{{ env_var('POSTGRES_HOST') }}"
#       user: "{{ env_var('POSTGRES_USER') }}"
#       password: "{{ env_var('POSTGRES_PASSWORD') }}"
#       port: "{{ env_var('POSTGRES_PORT') }}"
#       dbname: "{{ env_var('POSTGRES_DB') }}"
#       schema: warehouse
#       threads: 4

warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: warehouse
      threads: 4