
version: '3.9'
services:
  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    volumes:
      - ./MinIO/storage:/data
      - ./MinIO/config:/root/.minio
    ports:
      - "9000:9000"
      - "9090:9090"
    env_file:
      - ./.env
    command: server /data --console-address ":9090"
    networks:
      - de_network

  mc:
    image: minio/mc
    container_name: mc
    hostname: mc
    env_file:
      - ./.env
    entrypoint: >
          /bin/sh -c " until (/usr/bin/mc config host add minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1;done; /usr/bin/mc mb minio/warehouse; /usr/bin/mc policy set public minio/warehouse; exit 0; "
    depends_on:
      - minio
    networks:
      - de_network

  de_mysql:
    image: mysql:8.0
    container_name: de_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./storage/de_mysql_data:/var/lib/mysql
      - ./datasets:/tmp/datasets
    env_file:
      - ./.env
    networks:
      - de_network

  de_psql:
    container_name: de_psql
    image: postgres:15-alpine
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./storage/de_postgres_data:/var/lib/postgresql/data
    networks:
      - de_network

  postgres_metabase:
    image: postgres:15-alpine
    container_name: postgres_metabase
    environment:
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_password
      POSTGRES_DB: metabase_db
    volumes:
      - ./storage/postgres_metabase_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Sử dụng port 5433 để tránh xung đột với de_psql
    networks:
      - de_network

  de_metabase:
    image: metabase/metabase:v0.45.0
    container_name: de_metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data  # Volume này vẫn giữ để log hoặc dữ liệu tạm
    env_file:
      - ./.env
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_HOST: postgres_metabase  # Kết nối với service postgres_metabase
    depends_on:
      - postgres_metabase
    networks:
      - de_network

  de_dagster:
    build:
      context: ./dagster/
    container_name: de_dagster
    image: de_dagster

  de_dagster_dagit:
    image: de_dagster:latest
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3001"
      - -w
      - workspace.yaml
    container_name: de_dagster_dagit
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - ./.env
    networks:
      - de_network

  de_dagster_daemon:
    image: de_dagster:latest
    entrypoint:
      - dagster-daemon
      - run
    container_name: de_dagster_daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - ./.env
    networks:
      - de_network

  etl_pipeline:
    build:
      context: ./etl_pipeline
      dockerfile: ./Dockerfile
    container_name: etl_pipeline
    image: etl_pipeline:latest
    volumes:
      - ./etl_pipeline:/opt/dagster/app
    env_file:
      - ./.env
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
    name: de_network

volumes:
  postgres_metabase_data:
  metabase-data: