# name: 'warehouse_tests'
# version: '1.0.0'
# config-version: 2

# profile: 'warehouse'
# # dbt compile --profiles-dir /opt/dagster/app/etl_pipeline/dbt/
# model-paths: ["models"]
# test-paths: ["tests"]
# seed-paths: ["seeds"]
# macro-paths: ["macros"]

# target-path: "target"
# clean-targets:
#   - "target"
#   - "dbt_modules"

# models:
#   warehouse:
#     +materialized: table
#     +schema: warehouse

name: 'warehouse_tests'
version: '1.0.0'
config-version: 2

profile: 'warehouse'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  warehouse_tests:
    warehouse:
      +materialized: table
      +schema: warehouse
