# # version: 2

# # models:
# #   - name: dim_customer
# #     columns:
# #       - name: customer_key
# #         tests:
# #           - not_null
# #           - unique
# #       - name: customer_id
# #         tests:
# #           - not_null
# #       - name: birthday
# #         tests:
# #           - not_null
# #           - dbt_utils.acceptable_date:
# #               start_date: "1900-01-01"
# #               end_date: "CURRENT_DATE"

# #   - name: dim_product
# #     columns:
# #       - name: product_key
# #         tests:
# #           - not_null
# #           - unique
# #       - name: product_id
# #         tests:
# #           - not_null
# #       - name: start_date
# #         tests:
# #           - not_null
# #           - dbt_utils.acceptable_date:
# #               start_date: "1900-01-01"
# #               end_date: "CURRENT_DATE"
# #       - name: cost
# #         tests:
# #           - not_null
# #           - dbt_utils.at_least_zero

# #   - name: fact_sales
# #     columns:
# #       - name: order_number
# #         tests:
# #           - not_null
# #       - name: product_key
# #         tests:
# #           - not_null
# #           - relationships:
# #               to: ref('warehouse_dim_product')
# #               field: product_key
# #       - name: customer_key
# #         tests:
# #           - not_null
# #           - relationships:
# #               to: ref('warehouse_dim_customer')
# #               field: customer_key
# #       - name: order_date
# #         tests:
# #           - not_null
# #           - dbt_utils.acceptable_date:
# #               start_date: "1900-01-01"
# #               end_date: "CURRENT_DATE"
# #       - name: sales_amount
# #         tests:
# #           - not_null
# #           - dbt_utils.at_least_zero
# #       - name: quantity
# #         tests:
# #           - not_null
# #           - dbt_utils.at_least_zero

# # version: 2

# # sources:
# #   - name: warehouse
# #     schema: warehouse
# #     tables:
# #       - name: warehouse_dim_customer
# #       - name: warehouse_dim_product
# #       - name: warehouse_fact_sales

# # models:
# #   - name: warehouse_dim_customer
# #     columns:
# #       - name: customer_key
# #         tests:
# #           - not_null
# #           - unique
# #       - name: customer_id
# #         tests:
# #           - not_null
# #       - name: birthday
# #         tests:
# #           - not_null
# #           - dbt_utils.acceptable_date:
# #               start_date: "1900-01-01"
# #               end_date: "CURRENT_DATE"

# #   - name: warehouse_dim_product
# #     columns:
# #       - name: product_key
# #         tests:
# #           - not_null
# #           - unique
# #       - name: product_id
# #         tests:
# #           - not_null
# #       - name: start_date
# #         tests:
# #           - not_null
# #           - dbt_utils.acceptable_date:
# #               start_date: "1900-01-01"
# #               end_date: "CURRENT_DATE"
# #       - name: cost
# #         tests:
# #           - not_null
# #           - dbt_utils.at_least_zero

# #   - name: warehouse_fact_sales
# #     columns:
# #       - name: order_number
# #         tests:
# #           - not_null
# #       - name: product_key
# #         tests:
# #           - not_null
# #           - relationships:
# #               to: ref('warehouse_dim_product')
# #               field: product_key
# #       - name: customer_key
# #         tests:
# #           - not_null
# #           - relationships:
# #               to: ref('warehouse_dim_customer')
# #               field: customer_key
# #       - name: order_date
# #         tests:
# #           - not_null
# #           - dbt_utils.acceptable_date:
# #               start_date: "1900-01-01"
# #               end_date: "CURRENT_DATE"
# #       - name: sales_amount
# #         tests:
# #           - not_null
# #           - dbt_utils.at_least_zero
# #       - name: quantity
# #         tests:
# #           - not_null
# #           - dbt_utils.at_least_zero

# version: 2

# sources:
#   - name: warehouse
#     schema: warehouse
#     tables:
#       - name: dim_customer
#       - name: dim_product
#       - name: fact_sales

# models:
#   - name: dim_customer
#     columns:
#       - name: customer_key
#         tests:
#           - not_null
#           - unique
#       - name: customer_id
#         tests:
#           - not_null
#       - name: birthday
#         tests:
#           - not_null
#           - dbt_utils.acceptable_date:
#               start_date: "1900-01-01"
#               end_date: "CURRENT_DATE"

#   - name: dim_product
#     columns:
#       - name: product_key
#         tests:
#           - not_null
#           - unique
#       - name: product_id
#         tests:
#           - not_null
#       - name: start_date
#         tests:
#           - not_null
#           - dbt_utils.acceptable_date:
#               start_date: "1900-01-01"
#               end_date: "CURRENT_DATE"
#       - name: cost
#         tests:
#           - not_null
#           - dbt_utils.at_least_zero

#   - name: fact_sales
#     columns:
#       - name: order_number
#         tests:
#           - not_null
#       - name: product_key
#         tests:
#           - not_null
#           - relationships:
#               to: ref('dim_product')
#               field: product_key
#       - name: customer_key
#         tests:
#           - not_null
#           - relationships:
#               to: ref('dim_customer')
#               field: customer_key
#       - name: order_date
#         tests:
#           - not_null
#           - dbt_utils.acceptable_date:
#               start_date: "1900-01-01"
#               end_date: "CURRENT_DATE"
#       - name: sales_amount
#         tests:
#           - not_null
#           - dbt_utils.at_least_zero
#       - name: quantity
#         tests:
#           - not_null
#           - dbt_utils.at_least_zero

version: 2

sources:
  - name: warehouse
    schema: warehouse
    tables:
      - name: warehouse_dim_customer
      - name: warehouse_dim_product
      - name: warehouse_fact_sales

models:
  - name: dim_customer
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      # - name: birthday
      #   tests:
      #     - not_null

  - name: dim_product
    columns:
      - name: product_key
        tests:
          - not_null
          - unique
      - name: product_id
        tests:
          - not_null
      # - name: start_date
      #   tests:
      #     - not_null
      # - name: cost
      #   tests:
      #     - not_null

  - name: fact_sales
    columns:
      - name: order_number
        tests:
          - not_null
      - name: product_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      # - name: order_date
      #   tests:
      #     - not_null
      - name: sales_amount
      #   tests:
      #     - not_null
      # - name: quantity
      #   tests:
      #     - not_null
