
version: 2

sources:
  - name: warehouse
    schema: warehouse
    tables:
      - name: warehouse_dim_customer
      - name: warehouse_dim_product
      - name: warehouse_fact_sales

models:
  - name: dim_customer
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null


  - name: dim_product
    columns:
      - name: product_key
        tests:
          - not_null
          - unique
      - name: product_id
        tests:
          - not_null


  - name: fact_sales
    columns:
      - name: order_number
        tests:
          - not_null
      - name: product_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key

